package com.retailer.rewards.entity;

import java.util.ArrayList;
import java.util.List;

import jakarta.persistence.*;

/**
 * JPA Entity representing a customer in the retailer rewards system.
 * 
 * This entity maps to the {@code customer} table in the database and represents
 * individual customers who participate in the rewards program. Each customer
 * can
 * have multiple transactions associated with them, which are used to calculate
 * reward points and analyze customer spending behavior.
 * 
 * <p>
 * <b>Database Mapping:</b>
 * <ul>
 * <li>Table Name: {@code customer}</li>
 * <li>Primary Key: {@code customer_id} (auto-generated identity)</li>
 * </ul>
 * </p>
 * 
 * <p>
 * <b>Relationships:</b>
 * <ul>
 * <li>One-to-Many: A customer has many transactions
 * ({@code TransactionEntity})</li>
 * <li>Cascade Policy: All cascading operations (persist, merge, remove) are
 * propagated to transactions</li>
 * <li>Fetch Strategy: Transactions are lazily loaded to optimize database
 * queries</li>
 * </ul>
 * </p>
 * 
 * <p>
 * <b>Business Logic:</b>
 * Each customer's transactions are analyzed to:
 * <ul>
 * <li>Calculate total spending and reward points</li>
 * <li>Generate monthly reward summaries</li>
 * <li>Track customer activity and engagement</li>
 * </ul>
 * </p>
 * 
 * @author Karthik BK
 * @version 1.0
 * @since 1.0
 * @see com.retailer.rewards.entity.TransactionEntity
 */
@Entity
@Table(name = "customer")
public class CustomerEntity {

    /**
     * Unique identifier for the customer.
     * 
     * <p>
     * This field is the primary key in the {@code customer} table, automatically
     * generated by the database using an identity strategy (auto-increment).
     * Each customer has a unique customer ID that is never reused.
     * </p>
     * 
     * <p>
     * <b>Database Column:</b> {@code customer_id}
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "customer_id")
    private Long customerId;

    /**
     * The name of the customer.
     * 
     * <p>
     * This field stores the full name of the customer as provided during
     * registration
     * or customer information updates. The name is used for identification and
     * reporting purposes within the rewards system.
     * </p>
     * 
     * <p>
     * <b>Database Column:</b> {@code customer_name}
     * </p>
     */
    @Column(name = "customer_name")
    private String customerName;

    /**
     * Collection of transactions associated with this customer.
     * 
     * <p>
     * This field maintains a one-to-many relationship with
     * {@code TransactionEntity} objects.
     * Each transaction represents a purchase made by the customer and is used to
     * calculate
     * reward points and generate customer analytics.
     * </p>
     * 
     * <p>
     * <b>Relationship Configuration:</b>
     * <ul>
     * <li>Mapped By: {@code customerEntity} (inverse side of the relationship)</li>
     * <li>Cascade Type: All (persist, merge, remove operations cascade to
     * transactions)</li>
     * <li>Fetch Type: Lazy (transactions are loaded only when explicitly
     * accessed)</li>
     * </ul>
     * </p>
     * 
     * <p>
     * <b>Initialization:</b> The list is initialized with an empty
     * {@code ArrayList} to prevent
     * null pointer exceptions when accessing the collection.
     * </p>
     */
    @OneToMany(mappedBy = "customerEntity", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<TransactionEntity> transactions = new ArrayList<>();

    /**
     * Gets the unique identifier for this customer.
     * 
     * @return the customer ID, or null if the customer has not been persisted to
     *         the database
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * Sets the unique identifier for this customer.
     * 
     * <p>
     * <b>Note:</b> This field is auto-generated by the database. Typically, this
     * method
     * should not be called manually except for testing or database synchronization
     * purposes.
     * </p>
     * 
     * @param customerId the customer ID to set. Should be a positive long value.
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * Gets the name of this customer.
     * 
     * @return the customer name
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the name of this customer.
     * 
     * @param customerName the customer name to set. Must not be null.
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * Gets the list of transactions associated with this customer.
     * 
     * <p>
     * <b>Note:</b> Due to the lazy fetch strategy, accessing this list will trigger
     * a database query if the entity was loaded from the database and the
     * transactions
     * collection hasn't been loaded yet. Ensure this is called within an active
     * transaction context.
     * </p>
     * 
     * @return the list of transactions, or an empty list if no transactions exist
     */
    public List<TransactionEntity> getTransactions() {
        return transactions;
    }

    /**
     * Sets the list of transactions associated with this customer.
     * 
     * <p>
     * <b>Note:</b> Replacing the entire list is generally not recommended. Instead,
     * use list
     * manipulation methods (add, remove) to maintain the relationship integrity. If
     * this method
     * is used, ensure cascade operations are properly configured.
     * </p>
     * 
     * @param transactions the list of transactions to set. Must not be null; use an
     *                     empty list if no transactions exist.
     */
    public void setTransactions(List<TransactionEntity> transactions) {
        this.transactions = transactions;
    }
}
