package com.retailer.rewards.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * JPA Entity representing a customer transaction in the retailer rewards
 * system.
 * 
 * This entity maps to the {@code transactions} table in the database and
 * represents
 * individual purchase transactions made by customers. Each transaction belongs
 * to a
 * specific customer and contains purchase information including the transaction
 * date
 * and amount. Transactions are the foundation for calculating reward points
 * according
 * to the retailer's rewards program rules.
 * 
 * <p>
 * <b>Database Mapping:</b>
 * <ul>
 * <li>Table Name: {@code transactions}</li>
 * <li>Primary Key: {@code transaction_id} (auto-generated identity)</li>
 * </ul>
 * </p>
 * 
 * <p>
 * <b>Relationships:</b>
 * <ul>
 * <li>Many-to-One: Many transactions belong to one customer
 * ({@code CustomerEntity})</li>
 * <li>Foreign Key: {@code customer_id} references the {@code customer} table's
 * {@code customer_id}</li>
 * <li>Fetch Strategy: Customer entity is lazily loaded to optimize database
 * queries</li>
 * </ul>
 * </p>
 * 
 * <p>
 * <b>Business Logic:</b>
 * Each transaction is used to:
 * <ul>
 * <li>Calculate individual transaction reward points based on purchase
 * amount</li>
 * <li>Generate monthly reward summaries for customers</li>
 * <li>Analyze customer spending patterns and behavior</li>
 * <li>Support rewards program reporting and analytics</li>
 * </ul>
 * </p>
 * 
 * @author Karthik BK
 * @version 1.0
 * @since 1.0
 * @see com.retailer.rewards.entity.CustomerEntity
 */
@Entity
@Table(name = "transactions")
public class TransactionEntity {

    /**
     * Unique identifier for the transaction.
     * 
     * <p>
     * This field is the primary key in the {@code transactions} table,
     * automatically
     * generated by the database using an identity strategy (auto-increment). Each
     * transaction
     * has a unique transaction ID that is never reused.
     * </p>
     * 
     * <p>
     * <b>Database Column:</b> {@code transaction_id}
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "transaction_id")
    private Long transactionId;

    /**
     * The date when the transaction occurred.
     * 
     * <p>
     * This field stores the date of the customer's purchase. The transaction date
     * is used for
     * filtering transactions in reward calculations (e.g., calculating rewards for
     * transactions
     * after a specific cutoff date), monthly aggregations, and historical analysis.
     * </p>
     * 
     * <p>
     * <b>Database Column:</b> {@code transaction_date}
     * </p>
     */
    @Column(name = "transaction_date")
    private LocalDate transactionDate;

    /**
     * The purchase amount for this transaction.
     * 
     * <p>
     * This field stores the monetary value of the transaction as a
     * {@code BigDecimal} to ensure
     * precision for financial calculations. The amount is the basis for reward
     * point calculation,
     * where the reward program rules determine how many points are earned per
     * currency unit spent.
     * </p>
     * 
     * <p>
     * <b>Database Column:</b> {@code amount}
     * </p>
     */
    @Column(name = "amount")
    private BigDecimal amount;

    /**
     * Reference to the customer who made this transaction.
     * 
     * <p>
     * This field maintains a many-to-one relationship with {@code CustomerEntity}.
     * Multiple
     * transactions can belong to the same customer. The relationship is configured
     * with lazy
     * loading to optimize database queries by avoiding unnecessary customer entity
     * fetches.
     * </p>
     * 
     * <p>
     * <b>Relationship Configuration:</b>
     * <ul>
     * <li>Fetch Type: Lazy (customer is loaded only when explicitly accessed)</li>
     * <li>Foreign Key Column: {@code customer_id}</li>
     * <li>References: {@code customer.customer_id}</li>
     * </ul>
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", referencedColumnName = "customer_id")
    private CustomerEntity customerEntity;

    /**
     * Gets the unique identifier for this transaction.
     * 
     * @return the transaction ID, or null if the transaction has not been persisted
     *         to the database
     */
    public Long getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the unique identifier for this transaction.
     * 
     * <p>
     * <b>Note:</b> This field is auto-generated by the database. Typically, this
     * method should
     * not be called manually except for testing or database synchronization
     * purposes.
     * </p>
     * 
     * @param transactionId the transaction ID to set. Should be a positive long
     *                      value.
     */
    public void setTransactionId(Long transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Gets the date when this transaction occurred.
     * 
     * @return the transaction date in the format of {@code LocalDate}
     */
    public LocalDate getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the date when this transaction occurred.
     * 
     * @param transactionDate the transaction date to set. Must not be null.
     */
    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * Gets the purchase amount for this transaction.
     * 
     * @return the transaction amount as a {@code BigDecimal} to ensure financial
     *         precision
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the purchase amount for this transaction.
     * 
     * <p>
     * <b>Note:</b> {@code BigDecimal} is used to ensure accuracy for monetary
     * calculations.
     * Avoid using {@code Double} or {@code Float} for financial data.
     * </p>
     * 
     * @param amount the transaction amount to set. Must be a non-negative
     *               {@code BigDecimal} value.
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Gets the customer who made this transaction.
     * 
     * <p>
     * <b>Note:</b> Due to the lazy fetch strategy, accessing this field will
     * trigger a
     * database query if the entity was loaded from the database and the customer
     * hasn't been
     * loaded yet. Ensure this is called within an active transaction context if
     * needed.
     * </p>
     * 
     * @return the customer entity associated with this transaction, or null if not
     *         set
     */
    public CustomerEntity getCustomerEntity() {
        return customerEntity;
    }

    /**
     * Sets the customer who made this transaction.
     * 
     * <p>
     * <b>Note:</b> This method sets the many-to-one relationship with the customer.
     * Ensure
     * the provided customer entity is valid and managed by the persistence context
     * if using
     * within an active transaction.
     * </p>
     * 
     * @param customerEntity the customer entity to associate with this transaction.
     *                       Must not be null.
     */
    public void setCustomerEntity(CustomerEntity customerEntity) {
        this.customerEntity = customerEntity;
    }
}
